js_growth_table_DOM
mate-academy/js_growth_table_DOM pull request #100
Opened 2021-03-11 15:21 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/js_growth_table_DOM/)

2021-03-13 13:18 UTC, yashnyi requested changes
10 і 2 - магічні числа

2021-03-15 08:55 UTC, yashnyi approved these changes
gj

2021-03-15 10:40 UTC, Vladimir-Beliy approved these changes

2021-03-15 10:40 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +const minCount = 2;
count чего?

2026-02-02 19:53 UTC, closed without merging