develop
mate-academy/js_growth_table_DOM pull request #350
Opened 2022-12-03 11:59 UTC by panianchuk

https://panianchuk.github.io/js_growth_table_DOM/

2022-12-04 09:27 UTC, SanyaBratashchuk requested changes

2022-12-04 09:27 UTC, SanyaBratashchuk commented on src/scripts/main.js
> +});
move lengths to the variables

2022-12-05 00:15 UTC, ivanchuk-yurii requested changes

2022-12-05 00:15 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +    : btnAddRow.disabled = false;
```suggestion
  btnAddRow.disabled = tbody.children.length >= maxNumbersBlocks
```

2022-12-05 00:15 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +  }
it's better to use `switch case`

2022-12-06 16:02 UTC, k-zhdanova requested changes

2022-12-06 16:02 UTC, k-zhdanova commented on src/scripts/main.js
> +
Still not resolved for these cases 
<img width="850" alt="Screenshot 2022-12-06 at 19 59 33" src="https://user-images.githubusercontent.com/104555497/205961195-0d9666b1-2093-46a4-85b9-9db835c40406.png">

2023-12-29 10:46 UTC, closed without merging